SITE_NAME_TRAVELERFOLIO = "travelerfolio"
SITE_NAME_THESMARTLOCAL = "thesmartlocal"
SITE_NAME_ALVINOLOGY = "alvinology"
SITE_NAME_THEOCCASIONALTRAVELLER = "theoccasionaltraveller"
DIR_HTML = "data/html"
DIR_JSON = "data/json"
